### ISSUE TITLE
how changes are updated to 'live' website

### ISSUE THREAD

**Issue by jiyoungyoun** [knightjdr/youn-lab#1]
Hi, 

How are changes in the text/ content updated to the 'live' website?

I made small changes in the text under 'About' section (under src/markdown/about folder) and made changes  in the 'master' file instead of creating a new branch.

Does this change automatically update on the 'https://knightjdr.github.io/youn-lab' web or do I need to do something ?

**Comment by knightjdr** [comment]
You need to build and deploy the changes. This will push the changes to the `gh-pages` branch. You'll find these instructions in the `Deployment` section of the README.

**Comment by knightjdr** [comment]
All good?
